### ISSUE TITLE
Ability to rename tasks

### ISSUE THREAD

**Issue by PkKingX11** [KrishnaPravin/google-tasks-vscode-extension#16]
Basic functionality. Please add the ability to rename tasks and subtasks instead of deleting and recreating.
Tasks can have descriptions, sub-tasks and due dates which get lost when deleting.

**Comment by KrishnaPravin** [comment]
@PkKingX11 added in version [0.3.0](https://marketplace.visualstudio.com/items?itemName=KrishnaPravin.google-tasks)
