### ISSUE TITLE
It's a great plugin

### ISSUE THREAD

**Issue by qingfeng** [KrishnaPravin/google-tasks-vscode-extension#2]
It's a great plugin!
However, the following features would still be desired.
1. Manual refresh of synchronization
2. Can be set to hide completed tasks

Thank you.

**Comment by KrishnaPravin** [comment]
@qingfeng Thank you for letting me know. I was working on it. I was lazy about fixing a small issue.
But now I will take it as priority and fix it ASAP.

**Comment by KrishnaPravin** [comment]
@qingfeng check the latest version `0.2.0`. I hope the requested features are available.
Let me know if anything needs to be improved.

**Comment by qingfeng** [comment]
@KrishnaPravin thanks! 🎉
